### ISSUE TITLE
Deployment Sometimes Failes

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.applications#1]
```
Error: Cannot read property 'indexOf' of null
```

**Comment by href** [comment]
Travis has implemented build-stages, rendering our previous approach obsolete.

I implemented this again with build stages which are a better and more dependable approach. I also disabled builds of untagged commits, cutting the time to release in half.

There is one open issue as a result:
https://github.com/OneGov/onegov.applications/issues/2
